apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/mlinarik-bridge: "true"
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: DB_DATABASE
              value: xwiki
            - name: DB_HOST
              value: xwiki-db
            - name: DB_PASSWORD
              value: xwiki
            - name: DB_USER
              value: xwiki
            - name: INDEX_HOST
              value: xwiki-index
            - name: XWIKI_VERSION
              value: xwiki
          image: xwiki:stable-mysql-tomcat
          name: xwiki-web
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/local/xwiki
              name: xwiki-data
      restartPolicy: Always
      volumes:
        - name: xwiki-data
          persistentVolumeClaim:
            claimName: xwiki-data
