apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: xwiki-data
  name: xwiki-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
